# Generated by Django 2.1.7 on 2026-07-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_contestparticipation_calibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_exam',
            field=models.BooleanField(default=False),
        ),
    ]
