# Generated by Django 3.2.25 on 2026-07-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_contestparticipation_calibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acmcontestrank',
            name='submission_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='contest',
            name='allowed_ip_ranges',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='oicontestrank',
            name='submission_info',
            field=models.JSONField(default=dict),
        ),
    ]
