# Generated by Django 3.2.25 on 2026-06-04 03:12

from django.db import migrations, models
import django.db.models.deletion
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_problem_group_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='problemtag',
            options={'ordering': ('rank', 'name', 'id')},
        ),
        migrations.AlterField(
            model_name='problem',
            name='io_mode',
            field=models.JSONField(default=problem.models._default_io_mode),
        ),
        migrations.AlterField(
            model_name='problem',
            name='languages',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='samples',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statistic_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='problem',
            name='template',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_case_score',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='problem.course')),
            ],
            options={
                'db_table': 'chapter',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChapterProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(help_text='题号，对应 Problem._id', max_length=64)),
                ('type', models.CharField(choices=[('example', '例题'), ('exercise', '习题')], default='exercise', max_length=16)),
                ('order', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problem.chapter')),
            ],
            options={
                'db_table': 'chapter_problem',
                'ordering': ('order', 'id'),
                'unique_together': {('chapter', 'display_id')},
            },
        ),
    ]
